<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/05/12 18:53:39

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'sqlite:C:\\xampp\\htdocs\\proyectobase\\trunk\\data/sandbox.db',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
