<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/05/17 17:16:50
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => true,
  'app_sf_guard_plugin_algorithm_callable' => 'md5',
  'app_sf_guard_plugin_success_signin_url' => '@homepage',
  'app_sf_guard_plugin_success_signout_url' => '@loginpage',
));
